### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by NY-Guy** [yankee42/java-file-change-watcher#1]
I'm soooo sorry, don't know where else to ask this.
Newbie here...  This is exactly the program I've been looking for, but I must be missing something obvious.  Where, exactly, do I find the filewatch.jar file?  Am I supposed to create or compile it somehow?
Also there's no documentation about what the -v switch does, either in the github files or in the java help file.  I'm at a loss.
Apologies again if I'm braking up the wrong tree here.
Thank you

**Comment by yankee42** [comment]
Indeed, GitHub hides the download quite well: On the landing page (the "Code"-tab) there is on the right side "Releases". That is where you can download the jar-file.

The `-v`-Option simply means "verbose". It does print a few more infos on what the program is doing. Not very much though.
